### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by aaronbrethorst** [vizllx/DraggableYoutubeFloatingVideo#3]

**Comment by vizllx** [comment]
Thanks Aaron. I will fix the issues and then try to re-upload. Can you
please tell what size of gif image is supported for screenshot?



*Thanks and Regards,*


[image: Sandeep Mukherjee on about.me]

Sandeep Mukherjee
about.me/vizllx
    <http://about.me/vizllx>

**Comment by aaronbrethorst** [comment]
No GIFs. Only PNG and JPG.

**Comment by vizllx** [comment]
Added License
