### ISSUE TITLE
Pod...

### ISSUE THREAD

**Issue by paoloandrea** [vizllx/DraggableYoutubeFloatingVideo#5]
Please can you add the project to pod library.
www.cocoapods.org

**Comment by vizllx** [comment]
Yah, for sure. I will do it soon.. Also making the project in Swift will be releasing in a month.

**Comment by vikmeup** [comment]
Does not support CocoaPods
Do not see Swift version

**Comment by fukemy** [comment]
hello. does it support swift now?

**Comment by vizllx** [comment]
Yes, It does now!
